export const CHANGE_POST_MESSAGE = "CHANGE_POST_MESSAGE";
export const CHANGE_DIALOG_MESSAGE = "CHANGE_DIALOG_MESSAGE";
export const ADD_POST_MESSAGE = "ADD_POST_MESSAGE";
export const ADD_DIALOG_MESSAGE = "ADD_DIALOG_MESSAGE";
