export const ADD_MESSAGE = 'ADD_MESSAGE';
export  const ADD_MESSAGE_VALUE = 'ADD_MESSAGE_VALUE';
export const ADD_POST = 'ADD_POST';
export const ADD_POST_VALUE = 'ADD_POST_VALUE'
export const FOLLOW = "FOLLOW";
export const NOFOLLOW = "NOFOLLOW";
export const SET__USERS = "SET__USERS";
export const SET__PAGE = "SET__PAGE";
export const SET__TOTAL = "SET__TOTAL";
export const SET__PAGINATION = "SET__PAGINATION";
export const TOGGLE__PRELOADER = "TOGGLE__PRELOADER ";
export const SET__PROFILE = "SET__PROFILE"
export const SET_USER_DATA = 'SET_USER_DATA';
export const TOGGLE_FOLLOW_STATUS = 'TOGGLE_FOLLOW_STATUS'
export const SET_STATUS = 'SET_STATUS'
export const INITIALIZE_DATE = 'INITIALIZE_DATE'
export const SET_PHOTOS = 'SET_PHOTOS'